[package]
name = "memcrs"
version = "0.0.1"
authors = ["Dariusz Ostolski <dariusz.ostolski@gmail.com>"]
edition = "2018"


[lib]
name = "memcrs"
path = "src/lib.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
byte-unit = "4.0.11"
bytes = "1.0.1"
clap = "2.33.3"
dashmap = "4.0.2"
failure = { version = "0.1.8" }
failure_derive = { version = "0.1.8" }
futures = "0.3.14"
futures-util = "0.3.14"
log = "0.4.14"
socket2 = { version = "0.4.0", features = ["all"] }
num_cpus = "1.13.0"
num-derive = "0.3.3"
num-traits = "0.2.14"
rand = { version = "0.8.3", features = ["small_rng"] }
serde = "1.0.125"
serde_derive = "1.0.125"
tracing = "0.1.25"
tracing-attributes = "0.1.15"
tracing-log = "0.1.2"
tracing-subscriber = "0.2"
tokio = { version = "1.5.0", features = ["full"] }
tokio-util = { version = "0.6.6", features = ["full"] }


