[package]
name = "memcrs"
version = "0.0.1"
authors = ["Dariusz Ostolski <dariusz.ostolski@gmail.com>"]
edition = "2018"


[lib]
name = "memcrs"
path = "src/lib.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
byte-unit = "4.0.10"
bytes = "1.0.1"
clap = "2.33.3"
dashmap = "4.0.2"
failure = { version = "0.1.8" }
failure_derive = { version = "0.1.8" }
futures = "0.3.12"
futures-util = "0.3.12"
log = "0.4.14"
socket2 = { version = "0.4.0", features = ["all"] }
num_cpus = "1.13.0"
num-derive = "0.3.3"
num-traits = "0.2.14"
serde = "1.0.123"
serde_derive = "1.0.123"
tracing = "0.1.23"
tracing-attributes = "0.1.12"
tracing-log = "0.1.1"
tracing-subscriber = "0.2"
tokio = { version = "1.2.0", features = ["full"] }
tokio-util = { version = "0.6.3", features = ["full"] }


